"""Build data/katib.json: Kâtip Çelebi on Lepanto, the new fleet and 1572–73.

Source: Kâtip Çelebi (Hacı Halife, 1609–1657), Tuhfetü'l-kibâr fî esfâri'l-bihâr
(Istanbul: İbrahim Müteferrika, 1141/1729), ff. 42r (foot)–45r (top), the
sections from "(سفر صنغین دوننما)", the campaign of the broken fleet, to the
return of the fleet in Receb 981 (1573). Internet Archive McGillLibrary-104394-279
(McGill University Library). The scan's page index n relates to the folio
as n = 2 × (folio + 3) for a recto: f. 42r is n90, f. 45r is n96. Public domain.

The OCR cannot read Müteferrika's type, so the text was transcribed by eye from
page images at 2400 px. The print has no punctuation; the section words that
the print sets in the running text (ذكر سفاین كفار, مشورت, خروج سفاین اسلام …) are
used as unit titles. The Latin transliteration (simplified Turkish scholarly
style) and the English are this site's working versions (CC0). Uncertain
readings are marked [?] in the transliteration and named in the notes.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "katib.json"

# (section, title, Ottoman as printed, transliteration, English, note)
UNITS = [
 ("lepanto", "The campaign of the broken fleet",
  "(سفر صنغین دوننما)",
  "(Sefer-i sınğın donanma)",
  "(The campaign of the broken fleet)",
  "Sınğın donanma, 'the broken fleet', is the Ottoman name for the fleet lost at Lepanto. The heading stands at the foot of f. 42r, after two chronograms on the conquest of Cyprus."),
 ("lepanto", "The fleet before the battle",
  "مقدما سردار پرتو پاشا ایله قپودان علی پاشا قبرسدن ردوسه كلوب برقاچ ایام اول اطرافده ارامدن صكره كافر دوننماسندن اثر و خبر بلورمیوب كرید اطه‌سنه صالدیلر سواحلنی غارت ایدوب كزركن جزایر بكلربكیسی اولوج علی پاشا دخی یكرمی پاره كمی ایله كلوب ملحق اولدی اتفاقله واروب كفالونیه جزیره‌سن غارتدن صكره كورفز جزیره‌سنه چقوب نواحیسن یغما و تخریب بعده روم ایلی كنارنده وندیك قلاعندن سبوت و اولكون و بار نام حصارلرین الوب نیچه زمان دریاده كزوب كافر دوننماسندن اثر و خبر بلورمدی چونكه هنكام شتا قریب اولمشیدی لوند كمیلری دریابكلری كمیلرنده ارباب تیمار از قالوب برر بهانه ایله كتمشلر ایدی جنكجی و كوركجی قسمنك دخی برازی داغلوب بقیهٔ عسكر دوننما كمیلریله اینه‌بختی لیماننه كلوب وضع لنكر ایلدیلر",
  "Mukaddemâ serdâr Pertev Paşa ile Kapudan Ali Paşa Kıbrıs'dan Rodos'a gelüp birkaç eyyâm ol etrâfda aradıkdan sonra kâfir donanmasından eser ü haber bulamayup Girid adasına saldılar. Sevâhilini ğâret idüp gezerken Cezâyir beğlerbeğisi Uluç Ali Paşa dahi yigirmi pâre gemi ile gelüp mülhak oldı. İttifâkla varup Kefalonya cezîresin ğâretden sonra Korfuz cezîresine çıkup nevâhîsin yağmâ ve tahrîb, ba'dehu Rûm-ili kenârında Venedik kılâ'ından Sopot ve Ülgün ve Bar nâm hisârların alup nice zamân deryâda gezüp kâfir donanmasından eser ü haber bulamadı. Çünki hengâm-ı şitâ karîb olmışıdı, levend gemileri [ve] deryâ beğleri gemilerinde erbâb-ı tîmâr az kalup birer bahâne ile gitmişler idi; cengçi ve kürekçi kısmının dahi birazı dağılup bakıyye-i asker donanma gemileriyle İnebahtı limanına gelüp vaz'-ı lenger eylediler.",
  "Earlier, the commander Pertev Pasha and the Kapudan Ali Pasha came from Cyprus to Rhodes and, after searching those parts for some days without finding trace or news of the infidel fleet, made for the island of Crete. While they were raiding its coasts, Uluç Ali Pasha, governor-general of Algiers, joined them with twenty ships. Together they plundered the island of Cephalonia, then landed on the island of Corfu and sacked and wasted its districts; afterwards, on the coast of Rumelia, they took the Venetian fortresses called Sopot, Ülgün and Bar. For a long time they cruised the sea without finding trace or news of the infidel fleet. Since the winter season was near, few timar-holders were left in the levend ships and the ships of the sea-beys; they had gone off, each on some pretext. Some of the fighting men and the oarsmen had scattered too, and the rest of the army came with the ships of the fleet to the harbour of İnebahtı and cast anchor.",
  "Sopot, Ülgün and Bar are Sopoto in Albania, Ulcinj (Dulcigno) and Bar (Antivari) on the Montenegrin coast, taken in August 1571. Kâtip Çelebi wrote the Tuhfe in 1656. For the council and the battle he follows Peçevî closely (compare Peç. Battle [3]–[7]), but he adds the Christian order of battle, the names of the dead and a judgement of his own."),
 ("lepanto", "The infidel fleet",
  "اول محلده خبر النديكه كفار خاكسار كمیلری بهر حال كلوب دوننمای همایون ایله مقابله و مقاتله ایلمك مقرردر ذكر سفاین كفار یوز قدرغه وندیكدن كه هر برنده یوز جنكجی وار ایدی اون ایكی دخی پاپادن درت مالته‌دن اوتوز اسپانیه انابولیسندن اون دخی جنویزدن كه اسپانیایه تابع اولوب باشلری اوغلان قپودان دیدكلری اندریا ایدی اون دخی دوقه‌دن كه فلورینا ولایتنك دوقه‌سی و لیغورنا حاكمیدر درت دخی قلاوریدن اون ایكی چیچلیه‌دن درت پورتقالدن اون ایكی دخی كوكالی كمیلری جمله ایكیوز ایكی پاره چكدری یكرمی طقوز و یكرمی یدی اوتراق الك اشاغیسی دوردر اوتراقدر ایدی ماونه دخی وندیكدن كه هر برنده اوچر یوز جنكجی وار ایدی ایكی قلیون وندیكدن كه هر برنده بیكر جنكجی وار ایدی و یكرمی بارجه دخی وندیكدن هر برنده ایكیشر یوز نفر قونمشیدی بو كمیلرك سرداری روما قپودانی مارقوانتون و اسپانیا قپودانی جوان اوستریالو یعنی اوستریالو بشنجی قارلوس ایمپراطورك زنادن حاصل ولدی ایدی و وندیك قپودانی ساستیانو ونیر بو كه وندیك بكلرندن ایدی و دوقا قپودانی و جنویز قپودانی و ترانده نام كوكللولر قپودانی ایدی وندیكك كمیلرینك ازغه زیاده مضایقه‌سی اولوب اسپانیا كمیلری برمقدار چوریش بكسماد ویرمش ایدی اول دخی كمیاب ایدی بونلر مسینه‌ده جمع اولوب چقدیلر و اون یدنجی كونده حلومیج اوكنه كلدیلر وندیكدن فریادجی وارد[ق]چه دخی صبر ایدك زبون اولسونلر دیو تسلی ویررلردی اسپانیادن جنكه قادر یكرمی بر بیك نفر جمع اولوب جنویزده كمیلره كیرمشلر ایدی الاماندن طقوز بیك مالته‌دن و چیچلیه‌دن بر اولقدر دخی جمله یكرمی بش بیك اولوب ایكی ایله قرق التی بیك كافر دفتر اولنمش ایدی",
  "Ol mahalde haber alındı ki küffâr-ı hâksâr gemileri behemehâl gelüp donanma-yı hümâyûn ile mukâbele ve mukâtele eylemek mukarrerdür. Zikr-i sefâyin-i küffâr: Yüz kadırga Venedik'den ki her birinde yüz cengçi var idi; on iki dahi Papa'dan; dört Malta'dan; otuz İspanya Anapolisinden; on dahi Ceneviz'den ki İspanya'ya tâbi' olup başları Oğlan Kapudan didükleri Andrea idi; on dahi Duka'dan ki Florina vilâyetinin dukası ve Liğorna hâkimidür; dört dahi Kalavri[?]'den; on iki Çiçilya'dan; dört Portukal'dan; on iki dahi Kokalı[?] gemileri. Cümle ikiyüz iki pâre çekdiri; yigirmi dokuz ve yigirmi yedi oturak, eñ aşağısı dörder oturakdır idi. Mavna dahi Venedik'den ki her birinde üçer yüz cengçi var idi; iki kalyon Venedik'den ki her birinde biñer cengçi var idi; ve yigirmi barça dahi Venedik'den, her birinde ikişer yüz nefer konmışıdı. Bu gemilerin serdârı Roma kapudanı Mark Antonyo, ve İspanya kapudanı Cuvan Ostriyalu, ya'nî Ostriyalu beşinci Karlos imparatorun zinâdan hâsıl veledi idi; ve Venedik kapudanı Sastiyano Venyer, bu ki Venedik beğlerinden idi; ve Duka kapudanı ve Ceneviz kapudanı, ve Tirande[?] nâm Kokalılar[?] kapudanı idi. Venedik'in gemilerinin azığa ziyâde muzâyakası olup İspanya gemileri bir mikdâr çürüyiş beksimâd virmiş idi, ol dahi kem-yâb idi. Bunlar Mesina'da cem' olup çıkdılar ve on yedinci günde Halumiç[?] öñüne geldiler. Venedik'den feryâdcı vardıkça: 'Dahi sabr idüñ, zebûn olsunlar' deyü tesellî virirlerdi. İspanya'dan cenge kâdir yigirmi bir biñ nefer cem' olup Ceneviz'de gemilere girmişler idi; Alaman'dan dokuz biñ, Malta'dan ve Çiçilya'dan bir o kadar dahi, cümle yigirmi beş biñ olup ikisi ile kırk altı biñ kâfir defter olunmış idi.",
  "There news was received that the ships of the despicable infidels were coming at all events, and were resolved to meet and fight the imperial fleet. The ships of the infidels were these: a hundred galleys from Venice, each with a hundred fighting men; twelve from the Pope; four from Malta; thirty from Naples of Spain; ten from Genoa, which is subject to Spain, whose head was Andrea, whom they call the Boy Captain; ten from the Duke, who is duke of the land of Florence and lord of Livorno; four from Kalavri [?]; twelve from Sicily; four from Portugal; and twelve ships of the Kokalı [?]. In all, two hundred and two galleys, of twenty-nine and twenty-seven banks, and at the least four men to a bank. Galleasses from Venice as well, each with three hundred fighting men; two galleons from Venice, each with a thousand fighting men; and twenty barques from Venice, each carrying two hundred men. The commander of these ships was the captain of Rome, Marcantonio; and the captain of Spain was Don Juan of Austria, that is, the son born out of wedlock to the Emperor Charles V; the captain of Venice was Sebastiano Venier, one of the lords of Venice; and there were the captain of the Duke, the captain of Genoa, and one Tirande [?], captain of the Kokalı [?]. The Venetian ships were very short of provisions, and the Spanish ships had given them some rotten biscuit, and even that was scarce. They gathered at Messina and set out, and on the seventeenth day came before Halumiç [?]. Whenever a complaint came from the Venetians, they would console them: 'Be patient a little longer, let the others grow weak.' From Spain twenty-one thousand men fit for battle had gathered and gone aboard the ships at Genoa; from the Germans nine thousand; from Malta and Sicily as many again, twenty-five thousand in all; with the two, forty-six thousand infidels were entered in the register.",
  "The order of battle is Kâtip Çelebi's addition; he does not name his source. Several numbers and names are his own and differ from the League's figures: the capitulations promised two hundred galleys and fifty thousand men (Liga Forces [2]), the League brought six galleasses, and Portugal sent no ships. 'Oğlan Kapudan' is Gian Andrea Doria. Kalavri, Kokalı, Tirande and Halumiç are uncertain in reading and not identified here. The Venetian shortage of food and men, and the quarrels it caused, are also in the League's own articles on grain (Liga Money [6]) and in Venier's hanging of Spanish soldiers."),
 ("lepanto", "The council of war",
  "مشورت عسكر اسلام سردار پرتو پاشا و قپودان علی پاشا و جزایر بكلربكیسی اولوج علی پاشا و طرابلوس بكلربكیسی جعفر پاشا و خیر الدین پاشا اوغلی حسن پاشا و اون بش سنجاق بكی و سائر اعیان عسكر بریره كلوب مشاوره ایلدیلر اولوج علی پاشا جنكه رضا ویرمیوب دوننمامز ناقصدر و اثنای دریاده كزمكله كمیلر بوزغوندر سابقا كورفزدن اینه‌بختی‌یه دوندكده دونوشدر دیو سپاه و یكیچری اجازتلی و اجازتسز طاغلمشلردر بو بوغاز حصارلرندن كفار دوننماسی ایچری كیره‌مز چقملق محل خطردر دیدكده پرتو پاشا اكا تابع اولوب قپودان پاشا غیرت اسلام و عرض پادشاهی یوقیدر هر سفینه‌دن بشر اونر آدم ناقص اولمغله نه لازم كلور دیو سایری دخی بر بر اعتراضلر ایدوب جنكه اقدام كوستردكده علی پاشا چونكه دشمن اوزرینه عزیمتی مقرر ایتدیكز باری دریا طرفنه كیده‌لم دیوب قپودان پاشا كناری طوتمق اولیدر دیدی بو بابده چوق نزاع اولوب اولوج علی پاشا قانی خیر الدین پاشا ایله دشمن و طورغود ایله جنك كورنلر نیچون سویلمزلر بر كمی‌یه طوب طوقندیغی كبی غرق احتمالندن قره‌یه میل ایتسه كرك سائرلره باعث انهزام اولور دیو كوردی مفید اولمادی باری كمیلردن فانوسلری و بیوك بیراق و فلاندره‌لری كیدرك دیو نصیحت ایلدی قپودان استهزا ایتمكه طوتنجق اول دخی فارغ اولدی",
  "Meşveret-i asker-i İslâm: Serdâr Pertev Paşa ve Kapudan Ali Paşa ve Cezâyir beğlerbeğisi Uluç Ali Paşa ve Trablus beğlerbeğisi Ca'fer Paşa ve Hayreddîn Paşa oğlı Hasan Paşa ve on beş sancak beği ve sâ'ir a'yân-ı asker bir yire gelüp müşâvere eylediler. Uluç Ali Paşa cenge rızâ virmeyüp: 'Donanmamız nâkısdur, ve esnâ-yı deryâda gezmekle gemiler bozğundur; sâbıkâ Korfuz'dan İnebahtı'ya döndükde dönüşdür deyü sipâh ve yeñiçeri icâzetli ve icâzetsiz dağılmışlardur. Bu boğaz hisârlarından küffâr donanması içerü giremez; çıkmaklık mahall-i hatardur' didükde Pertev Paşa aña tâbi' olup; Kapudan Paşa: 'Gayret-i İslâm ve ırz-ı pâdişâhî yok mıdur? Her sefîneden beşer oner âdem nâkıs olmağla ne lâzım gelür?' deyü sâyiri dahi birer birer i'tirâzlar idüp cenge ikdâm gösterdükde, Ali Paşa: 'Çünki düşman üzerine azîmeti mukarrer itdiñüz, bârî deryâ tarafına gidelüm' diyüp Kapudan Paşa: 'Kenârı tutmak evlâdur' didi. Bu bâbda çok nizâ' olup Uluç Ali Paşa: 'Kanı Hayreddîn Paşa ile düşman ve Turğud ile ceng görenler? Niçün söylemezler? Bir gemiye top tokunduğı gibi ğark ihtimâlinden karaya meyl itse gerek; sâ'irlere bâ'is-i inhizâm olur' deyü gördi mufîd olmadı. 'Bârî gemilerden fânûsları ve büyük bayrak ve flandıraları gidereñ' deyü nasîhat eyledi. Kapudan istihzâ itmeğe tutıncak, ol dahi fârig oldı.",
  "The council of the army of Islam. The commander Pertev Pasha, the Kapudan Ali Pasha, Uluç Ali Pasha, governor-general of Algiers, Cafer Pasha, governor-general of Tripoli, Hasan Pasha son of Hayreddin Pasha, fifteen sancak-beys and the other notables of the army met and took counsel. Uluç Ali Pasha would not agree to battle: 'Our fleet is short of men, and the ships are worn out from cruising at sea. Earlier, when we turned back from Corfu to İnebahtı, the sipahis and Janissaries scattered, with leave and without, saying that this was the return. The infidel fleet cannot get in past the fortresses of this strait; to go out is the dangerous course.' Pertev Pasha followed him. But the Kapudan Pasha said: 'Is there no zeal for Islam, no honour of the Padishah? What does it matter if every ship is five or ten men short?' The others too raised objections one by one, and when he pressed for battle, Ali Pasha said: 'Since you have resolved to go against the enemy, at least let us take the open-sea side.' The Kapudan Pasha said: 'Better to hold the shore.' There was much quarrelling over this. Uluç Ali Pasha said: 'Where are those who fought the enemy with Hayreddin Pasha and with Turgut? Why do they not speak? As soon as a cannonball strikes a ship, for fear of sinking she will make for the land, and that will set the rest to flight.' When he saw it was of no use, he advised: 'At least take the lanterns and the great banners and pennants off the ships.' When the Kapudan began to mock him, he too gave up.",
  "Compare Peçevî's council (Peç. Battle [4]–[6]); Kâtip Çelebi adds the other commanders, Uluç Ali's reasons (the men had gone home, thinking the campaign over, and the enemy could not force the strait) and his last advice to strike the lanterns and flags that marked the flagships, which is the detail that decides the battle in Peçevî (Peç. Battle [7])."),
 ("lepanto", "The Kapudan",
  "مزبور قپودان نفسنده یارار و مقدم ایدی لكن دریا جنكلری كورمیوب قورصانلق فننی بلمز متهور و رشید بر كمسنه ایدی و كندی‌یه كلان اوامرده البته كفارك دوننماسی هر قنده ایسه اوزرینه واروب مقابل اوله‌سز والا معاتب اولورسز دیو فرمان اولنمغله جمله عسكری كندی رأینه تابع قلوب جنكی مقرر ایتدیلر",
  "Mezbûr kapudan nefsinde yarar ve mukaddem idi, lâkin deryâ cenkleri görmeyüp korsanlık fennini bilmez, mütehevvir ve reşîd bir kimesne idi. Ve kendüye gelen evâmirde: 'Elbette küffârın donanması her kanda ise üzerine varup mukâbil olasız, ve illâ mu'âteb olursız' deyü fermân olunmağla, cümle askeri kendü re'yine tâbi' kılup cengi mukarrer itdiler.",
  "The said Kapudan was capable and forward in himself, but he was a rash and headstrong man who had not seen sea battles and did not know the art of the corsair. And since he had been commanded in the orders sent to him: 'Wherever the infidel fleet may be, you shall at all costs go against it and meet it, or you will be called to account,' he made the whole army follow his opinion, and they resolved on battle.",
  "Müezzinzade Ali Pasha had been Ağa of the Janissaries before he was made Kapudan; he was a soldier, not a seaman. Peçevî gives the same orders in the Kapudan's own mouth: 'It is not my office I fear for, but my head' (Peç. Battle [5])."),
 ("lepanto", "The fleet goes out; the Bloody Cape",
  "خروج سفاین اسلام و انهزام قپودان مزبور كمال تهور و غرور ایله طقوزیوز یتمش طقوز جمادی الاولی‌سنك اون یدنجی بازار كونی قالقوب اینه‌بختی بوغازندن چقدیلر پرتو پاشا صول قوله و علی پاشا صاغ قوله كندی اورتایه كیروب جمله یوز سكسن پاره كمی ایله الای باغلدیلر موره‌دن [؟] حلومیج كنارنده مزبور بوغازه قریب بر بورون وار ایدی اول زماندن بروقانلی بورون دیرلر كفار دوننماسی اول بورون اردنده یاتردی اول محلده علی پاشا قپودانه خبر كوندروب كفارك بارجه و ماونه‌سی قلعه و مترسلر كبی دوكوب صاوشوب دونوب یانلردن یا كریدن كیره‌لم دیدكده قپودان پاشا بن پادشاهك دوننماسنه قاچدی نامن قومازم دیو یوریوب قارشو واردی",
  "Hurûc-ı sefâyin-i İslâm ve inhizâm-ı kapudan-ı mezbûr: Kemâl-i tehevvür ve ğurûr ile dokuzyüz yetmiş dokuz Cemâziyelevvelinin on yedinci bazar güni kalkup İnebahtı boğazından çıkdılar. Pertev Paşa sol kola ve Ali Paşa sağ kola, kendü ortaya girüp cümle yüz seksen pâre gemi ile alay bağladılar. Mora'dan[?] Halumiç[?] kenârında mezbûr boğaza karîb bir burun var idi; ol zamândan berü Kanlı Burun dirler. Küffâr donanması ol burun ardında yatardı. Ol mahalde Ali Paşa kapudana haber gönderüp: 'Küffârın barça ve mavnası kal'e ve metrisler gibidür; döğüp savuşup dönüp yanlardan ya gerüden[?] girelüm' didükde, Kapudan Paşa: 'Ben pâdişâhın donanmasına kaçdı nâmın koymazam' deyü yürüyüp karşu vardı.",
  "The ships of Islam go out, and the said Kapudan is routed. In utter rashness and pride they set out on Sunday, the seventeenth of Jumada I of 979, and came out of the strait of İnebahtı. Pertev Pasha took the left wing and Ali Pasha the right, and [the Kapudan] himself went into the centre; with a hundred and eighty ships in all they drew up their line. Near that strait, on the coast of Halumiç [?], there was a cape which since that time they call the Bloody Cape; the infidel fleet lay behind it. There Ali Pasha sent word to the Kapudan: 'The infidels' barques and galleasses are like fortresses and batteries. Let them fire and pass, and then let us turn and go in from the flanks or from behind [?].' The Kapudan Pasha said: 'I will not let the name \"it ran\" be set on the Padishah's fleet,' and he advanced and went straight at them.",
  "Seventeen Jumada I 979 is Sunday, 7 October 1571. Modern accounts put Uluç Ali on the Ottoman left, facing Doria on the seaward side, and Mehmed Şuluk on the right by the shore; Kâtip Çelebi's wings are as printed. Uluç Ali's advice about the galleasses, the six floating batteries the Venetians placed before the line, is the tactical point of the chapter; the words 'from the flanks or from behind' are uncertain in reading."),
 ("lepanto", "The battle",
  "در حال كافرك التی پاره كمیسی سچیلوب قانلو بوروندن طشره كلوب باقی كمیلری بورون اردنده صقلنوب كورنمزدی اهل اسلام كمیلری اول التی كمی‌یه چاتوب تمام الیسنی دخی سوندرمك ایله مقید ایكن سائر كمیلری بورون اردندن چقوب دوننمایی احاطه ایلیوب طوپه طوتدیلر بری طرفدن دخی مقتضای حال بریرده طوروب طوپلشور ایكن قپودان پاشا باشترده ایله الایدن سچیلوب اولا بركی‌یه چاتوب سوندرمك ایله مقید ایكن كفار اوچ فنرلرندن بیلوب اوشندی ایتدیلر ایكی پارچه باشترده‌یی ارایه الوب قپودانی شهید ایتدیلر ایكی اوغلی و ایچنده اولانلر اسیر اولوب پرتو پاشا كمیسنی دخی طوب ایله اوروب باتردیلر اوغلان ایله كندی دریایه دوشوب یوزركن حسن پاشا اوغلی محمود بك راست كلوب قانجه ایله كمیسنه الدی و بر خدمتكار اسبابی كیدروب باش كیدیجك ایاق پایدار اولماز",
  "Der-hâl kâfirin altı pâre gemisi seçilüp Kanlu Burun'dan taşra gelüp bâkî gemileri burun ardında saklanup görünmezdi. Ehl-i İslâm gemileri ol altı gemiye çatup tamâmı [?] dahi söndürmek ile mukayyed iken, sâ'ir gemileri burun ardından çıkup donanmayı ihâta eyleyüp topa tutdılar. Beri tarafdan dahi muktezâ-yı hâl bir yirde durup topleşür iken, Kapudan Paşa baştarda ile alaydan seçilüp evvelâ bir gemiye çatup söndürmek ile mukayyed iken, küffâr üç fenerlerinden bilüp üşendi[?] itdiler; iki pârça baştardeyi araya alup kapudanı şehîd itdiler. İki oğlı ve içinde olanlar esîr olup, Pertev Paşa gemisini dahi top ile urup batırdılar. Oğlan ile kendü deryâya düşüp yüzerken Hasan Paşa oğlı Mahmud Beğ râst gelüp kançe ile gemisine aldı ve bir hidmetkâr esbâbı giydirüp. Baş gidicek ayak pâydâr olmaz.",
  "At once six infidel ships came out alone from behind the Bloody Cape, while the rest of their ships lay hidden behind the cape and could not be seen. The ships of the people of Islam fell upon those six ships, and while they were busy trying to put them out of action, the other ships came out from behind the cape, surrounded the fleet and took it under fire. On this side too, as the moment required, they held their place and exchanged cannon fire; and the Kapudan Pasha broke from the line with his bastarda, fell first upon one ship and was busy putting it out of action, when the infidels, knowing him by his three lanterns, rushed upon him [?]: two of their ships took the bastarda between them and martyred the Kapudan. His two sons and those aboard were taken prisoner. They struck Pertev Pasha's ship with cannon and sank it too; he fell into the sea with a boy and was swimming when Mahmud Bey, son of Hasan Pasha, came upon him, took him into his ship with a boat, and dressed him in a servant's clothes. When the head goes, the foot does not stand.",
  "The six ships that came out first are the galleasses; Kâtip Çelebi, like the Ottoman commanders, took them for bait. The three lanterns are Peçevî's too (Peç. Battle [7]). The last sentence is a proverb: once the commander fell, the fleet broke. The verb printed اوشندی is uncertain."),
 ("lepanto", "Uluç Ali gets away",
  "سائر عسكره كلی انهزام واقع اولوب هر كس باشی قیوسنه دوشدی اولوج علی پاشا عتیق قورصان ایدی كمیسنده علامت قومیوب دریا طرفنه اچلمش ایدی قپودان كمیسی كردابه دوشدیكن كوردكده چكدرركن مالته قپودانی اوزرینه كلوب چاتوب الدی و قپودانك مسفورك [؟] باشنی كندی الیه كسوب برقاچ كافر كمیسنی دخی سوندردكدن صكره كفار غلبه ایتمكله جزایر كمیلری بری برلرینه قفادار اولوب جنك ایدرك موتون جانبنه طوغری چكدروب كتدیلر",
  "Sâ'ir askere küllî inhizâm vâkı' olup her kes başı kaygusuna düşdi. Uluç Ali Paşa atîk korsan idi; gemisinde alâmet koymayup deryâ tarafına açılmış idi. Kapudan gemisi girdâba düşdüğin gördükde, çekdirirken Malta kapudanı üzerine gelüp çatup aldı ve kapudanın [?] başını kendü eliyle kesüp, birkaç kâfir gemisini dahi söndürdükden sonra, küffâr ğalebe itmekle Cezâyir gemileri biri birlerine kafadâr olup ceng iderek Moton cânibine doğrı çekdirüp gitdiler.",
  "Utter rout fell on the rest of the army, and every man thought only of saving his head. Uluç Ali Pasha was an old corsair; he had left no mark on his ship and had stood out toward the open sea. When he saw the Kapudan's ship fall into the whirlpool, he rowed in, came upon the captain of Malta, grappled and took him, and cut off the [captain's?] head with his own hand; and after putting several infidel ships out of action, since the infidels were prevailing, the ships of Algiers, keeping close one behind another and fighting as they went, rowed straight off toward Moton.",
  "Uluç Ali struck his flags, as he had advised the others to do. The capture of the flagship of the Knights of Malta is in Cervantes too (DQ I.39 [3]). Moton is Modon (Methoni) in the Morea, where Kılıç Ali would shelter the new fleet the following year (Tuhfe 1572–73 [1]). The word before 'head' (printed مسفورك) is uncertain."),
 ("lepanto", "The dead",
  "عسكرك اكثری كفار ایله جنكده شهید اولوب محل جنك اناتولقو زومونه كنارینه قریب طوپوقلی صیغ یر اولمغله اون بش پاره كمی اوتوروب خلقی صویه دوكلدیلر بونلرك برازی قره‌یه چقوب خلاص اولوب باقیسی كیمی النوب كیمی غرق و هلاك اولدی اغریبوز بكی صاحب [؟] پاشازاده اسیر اولمش ایكن حسن پاشا كمیسی ایله قورتلوب پرتو پاشا محمود بك كمیسی ایله پره‌زه‌یه چقوب قاره‌دن اینه‌بختی‌یه كلدی شهدا چورم بكی كلابی [؟] قره حصار شرقی بكی احمد بك اندره [؟] بكی معمارزاده كلیبولی [؟] بكی احمد بك اینه‌بختی بكی فردوس ساقز بكی عبد الجبار مدللی بكی حضر صغه‌جق بكی قاره‌یتاق [؟] یغانكی [؟] علی مصر اسكندریه‌سی بكی شولوق و بر بك دخی جمله اون بر سنجاق بكی و ترسانه امینی و كتخداسی و قپودانلردن دومدومی [؟] علی مسلمان [؟] و غیری و بو سنجاقلرك سپاهیلری جمله شهید اولوب از كمسه قورتلوب كافر جمله التمش پاره قادرغه الوب آلات و اسبابی وندیك جبه‌خانه‌سنه قودی",
  "Askerin ekserî küffâr ile cenkde şehîd olup, mahall-i ceng Anatolikoz[?] kenârına karîb topuklı sığ yir olmağla on beş pâre gemi oturup halkı suya döküldiler. Bunların birazı karaya çıkup halâs olup bâkîsi kimi alınup kimi ğark u helâk oldı. Eğriboz beği Sâhib[?] Paşazâde esîr olmış iken Hasan Paşa gemisi ile kurtulup, Pertev Paşa Mahmud Beğ gemisi ile Preveze'ye çıkup karadan İnebahtı'ya geldi. Şühedâ: Çorum beği Gülâbî[?], Kara Hisâr-ı Şarkî beği Ahmed Beğ, Andıra[?] beği Mi'mârzâde, Gelibolı[?] beği Ahmed Beğ, İnebahtı beği Firdevs, Sakız beği Abdülcebbâr, Midilli beği Hızır, Sığacık beği Karayatak[?] Yeğânekî[?] Ali, Mısır İskenderiyesi beği Şuluk, ve bir beğ dahi, cümle on bir sancak beği; ve tersâne emîni ve kethudâsı, ve kapudanlardan Dumdumî[?] Ali, Müslümân[?] ve ğayrı; ve bu sancakların sipâhîleri cümle şehîd olup az kimesne kurtulup. Kâfir cümle altmış pâre kadırga alup âlât ve esbâbını Venedik cebehânesine kodı.",
  "Most of the army was martyred fighting the infidels. The place of the battle is near the coast of Anatolikoz, a shoaly, shallow place, and fifteen ships ran aground and their men poured into the water; some of them got ashore and were saved, and of the rest some were taken and some drowned and perished. The bey of Eğriboz, Sahib [?] Pashazade, had been taken prisoner but was rescued by Hasan Pasha's ship; Pertev Pasha got ashore at Preveze in Mahmud Bey's ship and came overland to İnebahtı. The martyrs: the bey of Çorum, Gülabi [?]; the bey of Karahisar-ı Şarki, Ahmed Bey; the bey of Andros [?], Mimarzade; the bey of Gelibolu [?], Ahmed Bey; the bey of İnebahtı, Firdevs; the bey of Chios, Abdülcebbar; the bey of Midilli, Hızır; the bey of Sığacık, Karayatak [?] Ali; the bey of Alexandria in Egypt, Şuluk; and one more bey: eleven sancak-beys in all; the intendant of the Arsenal and his steward; of the captains, Dumdumi [?] Ali, Müslüman [?] and others; and the sipahis of these sancaks, all martyred, few escaping. The infidel took sixty galleys in all and put their gear and equipment in the Venetian armoury.",
  "Anatolikoz is Aitoliko, the place Peçevî saw (Peç. Battle [8]). Şuluk is Mehmed Şuluk (Scirocco), who commanded the Ottoman right. Several names in the list are uncertain in reading and are given as printed; the identifications Andros and Gelibolu are conjectures. Kâtip Çelebi's sixty galleys taken differ from Peçevî's hundred and ninety lost (Peç. Fleet [1]): one counts the prizes, the other the whole loss."),
 ("lepanto", "The moral of the story",
  "قصه‌دن حصه بودركه دشمنك احوالنی سردارلر یوقلیوب تمام واقف اولدقدنصكره اكر مقاومته قدرت مرتبه‌سی وار ایسه ویله صلح ممكن ایكن جنكه اقدام اولنمیه اولندیغی تقدیرده كمال تحری و قانون اوزره جنك اوله سردار اولنلر بنفسه جنكه مباشرت ایتمیه‌لر یرنده طوروب سائر عسكری اقتضاسنه كوره قوللنه‌لر انهزام واقع اولوب امید كسلدكده ضروری بر جانبه چقمق دخی هنردر جمله عسكر قرلمقدن بر سردار الئمق ضرری ارتقدر خصوصا دریا جنكلرینی قره جنكنه قیاس ایتمیه‌لر جنك قانونلرینی تواریخده و حكما كتابلرنده كوره‌لر",
  "Kıssadan hisse budur ki: Düşmanın ahvâlini serdârlar yoklayup tamâm vâkıf oldukdan sonra, eğer mukâvemete kudret mertebesi var ise [da?], eğer sulh mümkin iken cenge ikdâm olunmaya; olunduğı takdîrde kemâl-i taharrî ve kânûn üzre ceng ola. Serdâr olanlar bi-nefsihi cenge mübâşeret itmeyeler; yirinde durup sâ'ir askeri iktizâsına göre kullanalar. İnhizâm vâkı' olup ümîd kesildükde zarûrî bir cânibe çıkmak dahi hünerdür; cümle asker kırılmakdan bir serdâr alınmak zararı artıkdur. Husûsâ deryâ cenklerini kara cengine kıyâs itmeyeler; ceng kânûnlarını tevârîhde ve hükemâ kitâblarında göreler.",
  "The moral of the story is this. Commanders should look into the condition of the enemy, and once they are fully informed, even if they have the strength to resist, battle should not be sought while peace is possible; if it is sought, it should be fought with the utmost care and according to rule. Those who command should not throw themselves into the fighting in person; they should keep their place and use the rest of the army as the moment requires. When the rout has come and hope is gone, to get away to one side of necessity is also a skill; the loss of a commander taken is greater than the whole army broken. Above all, let them not judge sea battles by land battles, and let them learn the rules of war in the histories and in the books of the sages.",
  "Kâtip Çelebi's own judgement, and the reason the Tuhfe was written: a book of naval history for the commanders of his own day, in the war of Crete. The sentence about the commander taken is read here as printed (ارتقدر, 'is greater'). Set it beside Cervantes's captive, who calls the day the day the nations learned the Turks were not invincible at sea (DQ I.39 [2])."),
 ("fleet", "Kılıç Ali made Kapudan",
  "توجیه مناصب و قپودانی قلیج علی پاشا پادشاه عالمپناه ادرنه‌ده ایكن جمادی الاخرك اوچنده اولوج علی پاشانك برادری كلوب بو خبر وحشت اثری كتوردی عامهٔ مسلمین غمكین اولوب بو خسارت قیامت اثر وقوعندن سبحان القادر الحكیم ان زلزلة الساعة لشیء عظیم دیو تعجب كنان استرجاع ایلدیلر اول اثناده منصب قپودانی مشار الیه شجاعتی و حسن تدبیری مقابله‌سنده مشار الیه اولوج علی پاشایه توجیه اولنوب اولوج لقبی قلیجه تبدیل قلندی القابنده لفظ مزبور یازلوب هر كس بعده قلیج علی پاشا دیدیلر دوشن سنجق بكلرینك یرلری ویرلوب مراد رئیسه دخی صغه‌جق سنجاغی توجیه اولندی",
  "Tevcîh-i menâsıb ve kapudanî-i Kılıç Ali Paşa: Pâdişâh-ı âlem-penâh Edirne'de iken Cemâziyelâhirin üçünde Uluç Ali Paşa'nın birâderi gelüp bu haber-i vahşet-eseri getürdi. Âmme-i müslimîn ğamgîn olup bu hasâret-i kıyâmet-eserin vukû'undan 'Sübhâne'l-kâdiri'l-hakîm, inne zelzelete's-sâ'ati şey'un azîm' deyü ta'accüb-künân istircâ' eylediler. Ol esnâda mansıb-ı kapudanî müşârün-ileyhin şecâ'ati ve hüsn-i tedbîri mukâbelesinde müşârün-ileyh Uluç Ali Paşa'ya tevcîh olunup Uluç lakabı Kılıc'a tebdîl kılındı; elkâbında lafz-ı mezbûr yazılup her kes ba'de Kılıç Ali Paşa didiler. Düşen sancak beğlerinin yirleri virilüp Murâd Re'îs'e dahi Sığacık sancağı tevcîh olundı.",
  "Offices bestowed, and Kılıç Ali Pasha made Kapudan. While the Padishah, refuge of the world, was at Edirne, on the third of Jumada II, Uluç Ali Pasha's brother came and brought this dreadful news. All the Muslims were grieved, and at this loss, like the Day of Judgement, they said in wonder, 'Glory to the Almighty, the All-Wise: the earthquake of the Hour is a mighty thing,' and spoke the words of return to God. At that time the office of Kapudan was bestowed on the said Uluç Ali Pasha in reward for his courage and good management, and the name Uluç was changed to Kılıç; the word was written in his titles, and afterwards everyone called him Kılıç Ali Pasha. The places of the sancak-beys who had fallen were given away, and Murad Reis received the sancak of Sığacık.",
  "Three Jumada II 979 is 23 October 1571. The Qur'anic words are 22:1; the 'words of return' are 'We are God's and to Him we return' (2:156), spoken at news of death. Peçevî tells the renaming more briefly (Peç. Battle [9]). Murad Reis is the corsair later famous for his raid on the Canaries (1585)."),
 ("fleet", "The Grand Vizier's measures",
  "تدارك و تدبیر وزیر اعظم محمد پاشا اول حینده پادشاه جم‌جاه مجددا كمیلر بنا اولنمق فرمان ایدوب ترسانه قربنده اولان باغچهٔ خاصه‌دن برمقدار یرلرن افراز و سكز كملو ترسانه احداث ایتدیلر وزیر اعظم محمد پاشا دخی وار قوتی بازویه كتوروب اول قیش ایچنده یوز اللی پاره قدرغه و سكز ماونه قوردردی",
  "Tedârük ve tedbîr-i vezîr-i a'zam Mehmed Paşa: Ol hînde pâdişâh-ı Cem-câh mücedded gemiler binâ olunmak fermân idüp tersâne kurbunda olan bağçe-i hâssadan bir mikdâr yirlerin ifrâz ve sekiz gemilü tersâne ihdâs itdiler. Vezîr-i a'zam Mehmed Paşa dahi var kuvveti bâzûya getürüp ol kış içinde yüz elli pâre kadırga ve sekiz mavna kurdurdı.",
  "The provisions and measures of the Grand Vizier Mehmed Pasha. At that time the Padishah, glorious as Jamshid, ordered that ships be built anew, and they set apart some of the ground of the private garden near the Arsenal and made there a new arsenal of eight slipways. The Grand Vizier Mehmed Pasha too put all his strength to the work and had a hundred and fifty galleys and eight galleasses built in the course of that winter.",
  "Peçevî gives the eight slipways but no count of ships built (Peç. Fleet [2]). The eight galleasses, 'mavna', are the Ottoman answer to the six Venetian galleasses of the battle."),
 ("fleet", "Anchors of silver, sails of satin",
  "قپودان قلیج پاشا هر بار دیرایدیكه تكنه بناسی اساندر ایكی یوز پاره كمی‌یه بش التی یوز لنكر و اكا كوره الات و یلكن و سائر لوازمی تكمیل محال كورینور محمد پاشا جواب ویروب پاشا حضرتلری بو دولت علیه‌نك قوت و قدرتی اول مرتبه‌دركه جمله دوننما لنكرلری كمشدن رسنلری ابریشمدن یلكنلری اطلسدن ایتمك فرمان اولنسه میسردر قنغی كمینك مهماتی یتشمزسه بو منوال اوزره بندن ال دیدكده علی پاشا الن ارقه‌سن یره قویوب تحسین و دعا ایلدی تحقیق بلدم كه بو دوننمایی سز تكمیل ایدرسز دیدی",
  "Kapudan Kılıç Paşa her bâr dir idi ki: 'Tekne binâsı âsândur; ikiyüz pâre gemiye beş altıyüz lenger ve aña göre âlât ve yelken ve sâ'ir levâzımı tekmîl muhâl görinür.' Mehmed Paşa cevâb virüp: 'Paşa hazretleri, bu devlet-i aliyyenin kuvvet ü kudreti ol mertebededür ki cümle donanma lengerleri gümüşden, resenleri ibrişimden, yelkenleri atlasdan itmek fermân olunsa müyesserdür. Kangı geminin mühimmâtı yetişmezse bu minvâl üzre benden al' didükde, Ali Paşa elin arkasın yire koyup tahsîn ü du'â eyledi: 'Tahkîk bildüm ki bu donanmayı siz tekmîl idersiz' didi.",
  "The Kapudan Kılıç Pasha kept saying: 'Building hulls is easy; but for two hundred ships, to complete five or six hundred anchors, and gear and sails and all the other needs in proportion, looks impossible.' Mehmed Pasha answered: 'Pasha, the power and might of this exalted state is such that if it were ordered to make the anchors of the whole fleet of silver, the cables of silk and the sails of satin, it could be done. Whatever ship lacks its stores, take them from me in this manner.' At this Ali Pasha laid the back of his hand on the ground, praised him and blessed him, and said: 'Now I know for certain that you will complete this fleet.'",
  "Taken from Peçevî, with small changes (Peç. Fleet [3]); in Peçevî Kılıç Ali kisses the Grand Vizier's hand. The phrase 'take it from me' settles the reading of Peçevî's more doubtful ending."),
 ("fleet", "Who paid for it",
  "نفس الامرده اول بهارده كمین جمله تداركلری كوروب بو قدر طوب و توفنك و آلات [؟] جنك كچن سنه اولمش ایدی كالاول بلكه دخی زیاده تكمیل ایتدی نزاع بونده قالدی كه بو كمیلری جمله میریدن ویریلن مال ایله می یاپدی یوقسه اعیان و اركان دولت امداد ایتدیلر می پچوی ایدر نه كمسنه‌یه كمی صالدیلر نه اقچه و امداد الدیلر اما ترسانهٔ عامره‌ده بعض اختیار قپودانلر یتشدكلری اول عصر رجالندن روایتله نقل ایدرلركه اعیان دولته هر كسه حاللو حالنجه كمی صالدیلر العهدة علی الراوی بونك صحتی خزینه دفترلرندن معلوم اولور",
  "Nefsü'l-emrde ol bahârda gemin [?] cümle tedârüklerin görüp, bu kadar top ve tüfenk ve âlât-ı [?] ceng geçen sene olmış idi ke'l-evvel, belki dahi ziyâde tekmîl itdi. Nizâ' bunda kaldı ki bu gemileri cümle mîrîden virilen mâl ile mi yapdı, yoksa a'yân ve erkân-ı devlet imdâd itdiler mi? Peçevî ider: 'Ne kimesneye gemi saldılar, ne akçe ve imdâd aldılar.' Ammâ Tersâne-i Âmire'de ba'z-ı ihtiyâr kapudanlar, yetişdükleri ol asr ricâlinden rivâyetle nakl iderler ki a'yân-ı devlete her kese hâllü hâlince gemi saldılar. El-uhdetü ale'r-râvî. Bunun sıhhati hazîne defterlerinden ma'lûm olur.",
  "In truth, by that spring he had seen to all the ships' provisions, and so many cannon and muskets and instruments of war had been completed as in the year before, or even more. The dispute remains whether he built these ships wholly with money given from the treasury, or whether the notables and pillars of the state contributed. Peçevî says: 'They laid no ship on anyone, nor took money or contributions.' But some old captains in the Imperial Arsenal relate, on the report of men of that age whom they knew, that a ship was laid on each of the notables of the state according to his means. The responsibility lies with the narrator; the truth of it can be known from the treasury registers.",
  "Kâtip Çelebi names his source and argues with it: this is the only place in the passage where he cites Peçevî by name (compare Peç. Fleet [4]). His appeal to the treasury registers is the historian's, not the chronicler's. The opening words are uncertain in reading."),
 ("after", "The guard of the sea, 1572",
  "سفر محافظه كفار خاكسار تركك بو ییل دوننما چقارمز اعتقادنده ایكن جمله ایكیوز اوتوز درت قدرغه و سكز ماونه ایله طقوزیوز سكسن صفرنده قلیج علی پاشا دریایه چقوب اوارین اوكنده اخشامه قریب وندیك دوننماسی بونلری كوردكده متحیر اولدیلر طرفیندن جنكه اقدام اولنمیوب برمقدار طوپلشدیلر دلاوران اسلام سنهٔ سابقه‌ده اولان هزیمت خطرندن احتراز ایدوب كفار دخی اثنای شبده اسپانیا دوننماسیله بریره كلمكله كندی قپودان اكرچه كمیلریز پر یراق و مكملدر هر وجهله مقابله‌یه قدرت واردر لكن كچن سنه اولان خسارت عظیمه‌دن لشكر اسلامك كوزی قورقمشدر محاربه‌ده ادنی هجوم ایله روكردان اولمق محتملدر لایق بودركه متون قلعه‌سی التنه كیروب دوننما حفظنه بذل مقدور ایده‌وز دیو چكدروب حصارك طوپی التنه كیردی و لازم اولان یرلره طوپلر چقاروب برقاچ پر یراق كمیلری لیمان اغزنده قودی ایرته‌سی علی السحر كفارك عظیم دوننماسی كلوب بر وجهله یقلاشمغه و قاره‌یه اردوكوب محاربه‌یه چاره بولمیوب برقاچ كون اول اطرافده دولاشوب مملكتلرینه رجوع ایتدكلرندنصكره سفاین اسلامیه متون التنه چقوب سلامتله ترسانهٔ عامره‌یه داخل اولدیلر",
  "Sefer-i muhâfaza: Küffâr-ı hâksâr 'Türk bu yıl donanma çıkarmaz' i'tikâdında iken, cümle ikiyüz otuz dört [?] kadırga ve sekiz mavna ile dokuzyüz seksen Safer'inde Kılıç Ali Paşa deryâya çıkup Avarin öñünde ahşama karîb Venedik donanması bunları gördükde mütehayyir oldılar. Tarafeynden cenge ikdâm olunmayup bir mikdâr topleşdiler; dilâverân-ı İslâm sene-i sâbıkada olan hezîmet hatarından ihtirâz idüp. Küffâr dahi esnâ-yı şebde İspanya donanmasıyla bir yire gelmekle, kendü kapudan: 'Egerçi gemilerimiz pür-yarak ve mükemmeldür, her vechile mukâbeleye kudret vardur; lâkin geçen sene olan hasâret-i azîmeden leşker-i İslâm'ın gözü korkmışdur; muhârebede ednâ hücûm ile rûgerdân olmak muhtemeldür. Lâyık budur ki Moton kal'esi altına girüp donanma hıfzına bezl-i makdûr idevüz' deyü çekdirüp hisârın topı altına girdi, ve lâzım olan yirlere toplar çıkarup birkaç pür-yarak gemileri liman ağzında kodı. Ertesi ale's-seher küffârın azîm donanması gelüp bir vechile yaklaşmağa ve karaya urduküp muhârebeye çâre bulamayup birkaç gün ol etrâfda dolaşup memleketlerine rücû' itdiklerinden sonra, sefâyin-i İslâmiyye Moton altından çıkup selâmetle Tersâne-i Âmire'ye dâhil oldılar.",
  "The campaign of guarding the sea. While the despicable infidels believed that 'the Turk will not put out a fleet this year', Kılıç Ali Pasha put to sea in Safar 980 with two hundred and thirty-four [?] galleys and eight galleasses. Toward evening, before Avarin, the Venetian fleet saw them and was astonished. Neither side pressed for battle; they exchanged some cannon fire, the brave men of Islam being wary of the danger of a rout like that of the year before. During the night the infidels joined the Spanish fleet; and [Kılıç Ali], the Kapudan himself, said: 'Our ships are fully armed and complete, and we have the strength to meet them in every way; but since the great loss of last year the army of Islam has been frightened, and in battle it is likely to turn its back at the slightest attack. The fitting course is to go in under the fortress of Moton and do all we can to preserve the fleet.' So he rowed in under the guns of the fortress, landed cannon where they were needed, and set some fully armed ships at the mouth of the harbour. The next morning at dawn the great fleet of the infidels came, but found no way to approach or to land and fight; after cruising about those parts for some days they went back to their countries, and the ships of Islam came out from under Moton and entered the Imperial Arsenal in safety.",
  "Safar 980 began in mid-June 1572; the encounter off Navarino (Avarin) and the League's failure at Modon (Moton) came in August–October. This is the other side of the campaign Cervantes's captive watched from the Ottoman oars: 'there I saw and observed how the opportunity of taking the whole Turkish fleet in harbour was lost' (DQ I.39 [4]); his master, Uluç Ali, 'took refuge at Modon' (DQ I.39 [5]). The number of galleys is uncertain in reading."),
 ("after", "Piyale Pasha's campaign, and the peace with Venice, 1573",
  "سفر پیاله پاشا و صلح وندیك كفار سابقا دوننمایی بوزمغله زیاده مغرور اولوب متونده دخی بی باك و بی پروا دوننمای همایون اوزرینه كلمكله دریای حمیت پادشاهی تموج ایدوب اخذ انتقام ایچون تكرار مستوفی كمیلر احضاری بابنده فرمان همایون صادر اولمغله مجددا كمیلر یاپلوب وزیر دلیر پیاله پاشا سردار تعیین بیورلدی طقوزیوز سكسن بر صفرینك ایكنجی كونی وافر عسكر ایله مملو ایكیوز اللی سكز قدرغه و اون ایكی ماونه ایله كفار خاكسار دوننماسنه مقابله ایچون چقوب اولونه‌دن [؟] ینه سواحلنه واردیلر اغر دوننما چقدوغن كفار اشیدوب حركته مجاللری اولمامغله پیاله پاشا و علی پاشا چكدروب پولیه یقالرینه واروب برقاچ پاره حربی قلعه‌لرینی الوب غارت ایتدكدنصكره وندیكك النده اولان كنارلره هجوم صددنده ایكن آستانه‌دن احكام شریفه وارد اولوب مفهومنده وندیك بكلری ایلچی كوندروب شمدی‌یه دك ظهوره كلن جرایم كذشته‌لرندن اعتذار و عبودیت اظهار ایلمكله استراحت رعایا و عسكر ایچون مضی ما مضی مفهومی اوزره [؟] الصلح خیر منطوقنجه صلح اولنوب مملكتلرینه امان همایون احسان اولنمشدر كركدر كه من بعد وندیك توابعی اولان ممالكی نهب و غارت ایلمیه‌سز انجق اسپانیا حكمنده اولان ولایاتی تخریبه بذل قدرت ایده‌سز دیو فرمان اولنمغله سردار و قپودان چیچلیه و انابولی سمتنه كیتمكه نیت ایتدیلر لكن شدید و مخالف یللر اسوب برقاچ كمیلر دخی شدت روزكاردن هلاك اولمغله دریا زمانی كچوب دره دولته عودت ایتدیلر و رجبده كلوب ترسانهٔ عامره‌یه كیردیلر",
  "Sefer-i Piyâle Paşa ve sulh-ı Venedik: Küffâr sâbıkâ donanmayı bozmağla ziyâde mağrûr olup Moton'da dahi bî-bâk ve bî-pervâ donanma-yı hümâyûn üzerine gelmekle, deryâ-yı hamiyyet-i pâdişâhî temevvüc idüp ahz-ı intikâm içün tekrâr müstevfî gemiler ihzârı bâbında fermân-ı hümâyûn sâdır olmağla mücedded gemiler yapılup vezîr-i dilîr Piyâle Paşa serdâr ta'yîn buyuruldı. Dokuzyüz seksen bir Safer'inin ikinci güni vâfir asker ile memlû ikiyüz elli sekiz kadırga ve on iki mavna ile küffâr-ı hâksâr donanmasına mukâbele içün çıkup Avlonya'dan [?] yine sevâhiline vardılar. Ağır donanma çıkduğın küffâr işidüp harekete mecâlleri olmamağla Piyâle Paşa ve Ali Paşa çekdirüp Pulya yakalarına varup birkaç pâre harbî kal'elerini alup ğâret itdikden sonra, Venedik'in elinde olan kenârlara hücûm sadedinde iken Âsitâne'den ahkâm-ı şerîfe vârid olup; mefhûmunda: 'Venedik beğleri ilçi gönderüp şimdiye dek zuhûra gelen cerâ'im-i güzeştelerinden i'tizâr ve ubûdiyyet izhâr eylemekle, istirâhat-i re'âyâ ve asker içün \"mazâ mâ mazâ\" mefhûmı üzre [?] \"es-sulhu hayr\" mantûkınca sulh olunup memleketlerine amân-ı hümâyûn ihsân olunmışdur. Gerekdür ki min-ba'd Venedik tevâbi'i olan memâliki nehb ü ğâret eylemeyesiz; ancak İspanya hükminde olan vilâyâtı tahrîbe bezl-i kudret idesiz' deyü fermân olunmağla, serdâr ve kapudan Çiçilya ve Anapoli semtine gitmeğe niyyet itdiler. Lâkin şedîd ve muhâlif yeller esüp birkaç gemiler dahi şiddet-i rüzgârdan helâk olmağla deryâ zamânı geçüp der-i devlete avdet itdiler, ve Receb'de gelüp Tersâne-i Âmire'ye girdiler.",
  "The campaign of Piyale Pasha, and the peace with Venice. Since the infidels had grown very proud at having broken the fleet before, and at Moton too had come against the imperial fleet heedless and unafraid, the sea of the Padishah's zeal surged, and an imperial order was issued to make ready a full fleet again to take revenge. New ships were built, and the valiant vizier Piyale Pasha was appointed commander. On the second day of Safar 981 he put out with two hundred and fifty-eight galleys and twelve galleasses, full of soldiers, to meet the fleet of the despicable infidels, and they came from Avlonya [?] again to the coasts. When the infidels heard that a heavy fleet had come out they had no strength to move, and Piyale Pasha and Ali Pasha rowed across to the shores of Apulia, took and plundered several enemy fortresses; and they were about to fall on the coasts held by Venice when noble orders arrived from the Threshold, to this effect: 'The lords of Venice have sent an envoy, excused themselves for the offences committed until now and professed their submission. For the repose of the subjects and the army, in the sense of \"let bygones be bygones\" and according to the words \"peace is better\", peace has been made and the imperial safe-conduct granted to their lands. Henceforth you must not plunder or raid the lands subject to Venice; but you shall do all you can to lay waste the lands under Spanish rule.' So the commander and the Kapudan meant to go toward Sicily and Naples; but violent contrary winds blew, several ships were lost in the storms, the sailing season passed, and they returned to the Porte, coming into the Imperial Arsenal in Receb.",
  "Two Safar 981 is 3 June 1573. The peace was signed at Istanbul on 7 March 1573, before the fleet sailed; Kâtip Çelebi tells it as the order that reached the commanders at sea. It is the peace the League's article forbade (Liga Faith [6]) and Ebussuud's fetva had set the terms for (Peç. Cyprus [4]): Venice asks pardon, keeps its other lands and gives up Cyprus, and the Ottoman fleet is turned against Spain. 'Peace is better' is Qur'an 4:128. A word between the two phrases is not read, and the place from which the fleet sailed is uncertain. The next section of the Tuhfe, on La Goleta and Tunis (1574), follows on the same page."),
]

SECTIONS = [
  ("lepanto", "The broken fleet (ff. 42r–44r)", "Tuhfe Lep.",
   "Kâtip Çelebi's account of Lepanto, written in 1656 for the commanders of his own day: the Christian order of battle as the Ottomans reckoned it, the council in which Uluç Ali warned against the galleasses and the lanterns, the Kapudan who would not let the fleet be called 'ran', the six ships that came out first from behind the Bloody Cape, the rout, the names of the dead, and a moral for commanders."),
  ("fleet", "Kılıç Ali and the new fleet (f. 44r–v)", "Tuhfe Fleet",
   "Uluç Ali made Kapudan and renamed Kılıç, a hundred and fifty galleys and eight galleasses built in a winter, Sokollu's anchors of silver taken from Peçevî, and a historian's dispute with his source over who paid."),
  ("after", "1572 and 1573: Modon and the peace (ff. 44v–45r)", "Tuhfe 1572–73",
   "The Ottoman side of the League's last campaigns: Kılıç Ali declining battle off Navarino and sheltering under the guns of Modon, and Piyale Pasha's cruise of 1573 cut short by the order announcing Venice's peace, with the fleet turned against Spain."),
]


def main():
    sections = []
    for sid, titel, zk, blurb in SECTIONS:
        units = []
        for s, label, ota, tr, en, note in UNITS:
            if s != sid:
                continue
            u = {"n": len(units) + 1, "orig": ota, "tr": tr, "en": en}
            if label:
                u["titel"] = label
            if note:
                u["note"] = note
            units.append(u)
        sections.append({"id": sid, "titel": titel, "zk": zk, "blurb": blurb, "units": units})
    sections[0]["units"][0]["label"] = True
    doc = {
        "id": "katib",
        "titel": "Kâtip Çelebi: The Broken Fleet",
        "autor": "Kâtip Çelebi (1609–1657)",
        "jahr": "1656 (printed 1729)",
        "sprache": "en",
        "orig_sprache": "ota",
        "zk": "Tuhfe",
        "quelle": "Kâtip Çelebi, Tuhfetü'l-kibâr fî esfâri'l-bihâr (Istanbul: İbrahim Müteferrika, 1141/1729), ff. 42r–45r; Internet Archive McGillLibrary-104394-279 (McGill University Library), scan pages n90–n96 (for a recto, n = 2 × (folio + 3)).",
        "hinweis": "The second Ottoman voice in this apparatus, and the first printed one: the Tuhfe was among the first books from the Ottoman press of İbrahim Müteferrika. Kâtip Çelebi, a clerk of the army and the greatest Ottoman scholar of his century, wrote this history of the naval wars in 1656, during the war of Crete, to teach commanders. For Lepanto he follows Peçevî (and names him once, to disagree), but he adds the Christian order of battle, the names of the dead, a judgement on the defeat and the campaigns of 1572 and 1573. The text is transcribed by eye from the page images, since the OCR cannot read the type; the print has no punctuation, and the division into units is the site's. The transliteration follows the usual simplified Turkish scholarly style; it and the English are this site's working versions (CC0), not a critical edition. Many proper names in the order of battle and the list of the dead are uncertain in reading; they are marked [?] and not forced into identifications. The words 'infidels' and 'people of Islam' are the document's, as 'Turks' and 'Christians' are the Venetian and Spanish sources'.",
        "rtl": True,
        "sections": sections,
    }
    OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"katib.json: {sum(len(s['units']) for s in sections)} units")


if __name__ == "__main__":
    main()
