"""Build data/pius.json: the Popes after the victory, 1571–1573.

Sources, all from the Bullarium Romanum, Turin edition (Bullarum diplomatum et
privilegiorum sanctorum Romanorum pontificum Taurinensis editio):
- Pius V, constitution CCXIII (21 December 1571): Turkish prisoners not to
  be released or sold while the war lasts; vol. VII (1862), pp. 957–958
  (kept in tools/pius_prisoners.py).
- Pius V, constitution CCXVII, Cum nos (12 March 1572): indulgences for all
  who help to continue the war; vol. VII (1862), pp. 967–969.
- Pius V, constitution CCXX (1572): Christians found as slaves among the Turks
  are to be set free with their goods by the officers of the Christian fleet;
  vol. VII, pp. 972–973.
- Gregory XIII, constitution XVII, Monet Apostolus (1 April 1573): the feast
  of the Rosary on the first Sunday of October, in thanksgiving for the
  victory of 7 October; vol. VIII (1863), pp. 44–46.
Internet Archive 04672031.7.emory.edu and 04672031.8.emory.edu (Emory
University, Pitts Theology Library); scan page n = printed page + 10 in both
volumes. Public domain.

The OCR is corrected by reading and checked against the page images. The
Bullarium's marginal summaries and footnotes are not carried except where a
note quotes them. The English is this site's working translation (CC0).
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pius_prisoners import PRISONERS  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "data" / "pius.json"

# (section, title, Latin, English, note)
UNITS = [
 # ------------------------------------------------------------ Cum nos
 ("war", "Indulgences and graces for those who help the war against the Turks",
  "Indulgentiae et gratiae pro adiuvantibus bellum contra Turcas.\nPius Papa V, universis christifidelibus praesentes litteras inspecturis, salutem et apostolicam benedictionem.",
  "Indulgences and graces for those who help the war against the Turks.\nPius V, Pope, to all the faithful in Christ who shall see these letters, greeting and apostolic blessing.",
  "Dated 12 March 1572, five months after the battle and seven weeks before Pius V's death on 1 May."),
 ("war", "The League and the victory",
  "Cum nos, pro pastoralis officii divinitus nobis iniuncti cura ac sollicitudine, divino auxilio adiuti, pro universae christianae reipublicae bono ac tutela, cum carissimo in Christo filio nostro Philippo Hispaniarum rege catholico ac dilectis filiis nobili viro duce et senatu Venetorum, adversus perfidissimum importunissimumque Turcarum tyrannum, efferata rabie cuncta christianae ditionis regna, provincias et alia loca incendiis, ferro, caedibus expugnantem atque vastantem, non minus salutare quam necessarium foedus iniverimus, iamque, admirabili Dei clementia et beneficio, navalem gloriosissimamque victoriam felicissime consecuti fuerimus, modoque a nobis principibus foederatis copiae tam maritimae quam terrestres, ut coeptam contra teterrimum hostem expeditionem, monstrante Deo, persequamur, summis viribus, summo studio, summa diligentia comparentur atque instruantur.",
  "Since we, in the care and solicitude of the pastoral office divinely laid upon us, with God's help, for the good and protection of the whole Christian commonwealth, have entered into a league no less salutary than necessary with our most dear son in Christ Philip, Catholic King of the Spains, and our beloved sons the noble Doge and Senate of the Venetians, against the most faithless and most troublesome tyrant of the Turks, who with savage fury storms and lays waste with fire, sword and slaughter all the kingdoms, provinces and other places of Christian rule; and since, by the wonderful mercy and kindness of God, we have most happily won a most glorious naval victory; and since forces both by sea and by land are now being gathered and equipped by us, the confederate princes, with the utmost strength, zeal and diligence, so that, God showing the way, we may pursue the expedition begun against that most foul enemy:",
  "The Pope speaks as one of the 'confederate princes'. The League's own articles oblige each partner to pay and arm for the war every year (Liga Forces [2]–[3], Liga Money [3])."),
 ("war", "'If God died for man, will man hesitate to die for God?'",
  "§ 1. Attamen, considerantes immanem Turcarum potentiam infinitamque multitudinem, qua potissimum res christianorum omni tempore miserabiliter perculisse atque afflixisse non ignoramus, magnopere idoneum et opportunum esse censemus, si christiani, maiori quo fieri poterit militum numero bellicoque apparatu, contra hostilem ferociam insurgere conabuntur: sic enim facilius sperandum est felicia nostra coepta, adiuvante Domino, fore in dies feliciora atque optatum exitum, gravi cum hostium formidine ac pernicie, habitura. Itaque decrevimus omnes et singulos fideles ad piissimum iustissimumque bellum, ubi de Iesu Christi Domini et Salvatoris nostri causa et gloria, christianique nominis salute, sicut omnes aperte vident, in primis agitur, monere, requirere et enixe hortari, prout monemus, requirimus et hortamur per praesentes, ut unusquisque sanctissimum hoc bellum vel personis vel facultatibus adiuvare velit. Negabit enim servus Domino opes temporales largiter exhibere, cum Dominus servum vivere faciat et habere, ipsique demum divitias largiatur aeternas? et si Deus subiit mortem pro homine, dubitabit homo mortem subire pro Deo?",
  "§ 1. Nevertheless, considering the enormous power and endless multitude of the Turks, with which, as we well know, they have at all times miserably struck and afflicted the affairs of the Christians, we judge it most fitting and opportune that Christians should strive to rise against the enemy's ferocity with the greatest possible number of soldiers and apparatus of war; for so it is easier to hope that our happy beginnings will, with the Lord's help, become happier day by day and reach the desired end, to the great fear and ruin of the enemy. We have therefore decided to warn, require and earnestly exhort all and every one of the faithful, as by these presents we do warn, require and exhort them, to this most pious and just war, in which, as all plainly see, the cause and glory of Jesus Christ our Lord and Saviour and the salvation of the Christian name are above all at stake, that each one be willing to help this most holy war either in person or with his means. For will the servant refuse to give his Lord temporal goods generously, when the Lord makes the servant live and have, and at last bestows on him eternal riches? And if God underwent death for man, will man hesitate to undergo death for God?",
  "The Pope's problem in the game: the Papacy had little fleet and much legitimacy, and paid its share from church revenues and indulgences. The appeal comes in the winter of 1571–72, when the Ottoman arsenal was rebuilding (Peç. Fleet [2]–[4])."),
 ("war", "The crusade indulgence",
  "Quod ut eo libentius et alacrius cuncti facere studeant, quo ex hoc spiritualibus muneribus et temporalibus quoque gratiis a nobis se refectos pariter et munitos esse cognoverint, de omnipotentis Dei misericordia ac beatorum apostolorum Petri et Pauli auctoritate confisi, ex illa, quam nobis Deus, licet indignis, ligandi et solvendi contulit, potestate, omnibus qui ad subveniendum huic sacro bello in personis propriis et expensis se se contulerint, necnon eis qui non in personis propriis illuc accesserint, sed suis tantum expensis, iuxta facultatem et qualitatem suam, viros idoneos destinaverint, donec milites nostri ibi fuerint, commoraturos; et illis similiter, qui, licet alienis expensis, propriis tamen personis belli laborem et pericula sustinuerint, ac demum eis, qui de bonis sibi a Deo collatis congruam ad id portionem benigne erogaverint, plenissimam et amplissimam omnium peccatorum suorum, de quibus corde contriti et ore confessi fuerint, et eamdemmet quam Romani Pontifices praedecessores nostri crucesignatis proficiscentibus ad subsidium Terrae Sanctae concedere soliti fuerunt, veniam, remissionem et absolutionem, tenore praesentium, indulgemus et elargimur. Bona insuper proficiscentium ad bellum huiusmodi, ex quo profecti fuerint, sub beati Petri et nostra protectione suscipimus, necnon ut talia sub archiepiscoporum et omnium praelatorum ecclesiae Dei tutela consistant; nullam de iis, quae, dum fuerint in dicto bello, quiete possident, sustineant quaestionem, sed integra maneant et quieta.",
  "And so that all may strive to do this the more willingly and eagerly, the more they know themselves refreshed and strengthened by us with spiritual gifts and temporal graces as well, trusting in the mercy of almighty God and the authority of the blessed apostles Peter and Paul, by the power of binding and loosing that God has conferred on us, though unworthy: to all who go in their own persons and at their own expense to help this holy war; to those who do not go in person but, at their own expense only, according to their means and rank, send suitable men to stay there as long as our soldiers are there; likewise to those who, though at another's expense, bear the labour and dangers of the war in their own persons; and lastly to those who, from the goods God has given them, kindly give a fitting portion for it: we grant and bestow by these presents the fullest and most ample pardon, remission and absolution of all their sins of which they are contrite in heart and have confessed with their mouth, the very same that the Roman Pontiffs our predecessors used to grant to crusaders going to the aid of the Holy Land. We also take the goods of those who set out for this war, from the time they set out, under the protection of Saint Peter and ourselves, and under the guardianship of the archbishops and all prelates of the Church of God; they shall suffer no suit concerning what they peaceably possess while they are in the said war, but it shall remain whole and undisturbed.",
  "The indulgence of the crusades, extended to those who only pay. The Bullarium's footnote refers to Innocent III's crusade bull Ad liberandam (1215)."),
 ("war", "Suits suspended, usury remitted",
  "§ 2. Quinimmo in quibusvis eorum causis et litibus a iudicibus, coram quibus vertuntur, omnino supersederi debere, donec de eorum obitu vel reditu certissime cognoscatur, statuimus et mandamus.\n§ 3. Ad usuras quoque, si iuramento teneantur alicui, non cogantur, verum absoluti maneant et quieti. Quod si quisquam contra attentare praesumpserit, per censuram ecclesiasticam, appellatione postposita, compescatur. Si quis autem creditorum, contra tenorem praesentium, ipsos ad solutionem coegerit usurarum, eum ad illarum restitutionem, appellatione etiam remota, simili censura compelli volumus. Iudaeos vero ad remittendas ipsis, ut praefertur, usuras etiam per principes et saecularem compelli praecipimus potestatem, et donec eis remiserint, tam in mercimoniis quam aliis rebus et commerciis, sub excommunicationis sententia per ordinarios promulganda, universis christifidelibus iubemus communionem omnimodam ipsis hebraeis denegari.",
  "§ 2. Moreover, we establish and command that in any of their cases and suits the judges before whom they are pending must wholly suspend proceedings until their death or return is known for certain.\n§ 3. Nor shall they be compelled to pay usury, even if bound to anyone by oath, but shall remain released and undisturbed. If anyone presumes to attempt the contrary, let him be restrained by ecclesiastical censure, all appeal set aside. And if any creditor, against the tenor of these presents, forces them to pay usury, we will that he be compelled by the like censure to restore it, appeal being likewise excluded. And we command that the Jews be compelled, by the princes and the secular power as well, to remit usury to them as aforesaid; and until they have remitted it, we order all the faithful, under sentence of excommunication to be pronounced by the ordinaries, to deny those Jews all dealings whatever, in trade and in other matters and business.",
  "The clause against the Jews repeats the crusade privileges of the thirteenth century and is carried as printed. It belongs to the same pontificate as Pius V's expulsion of the Jews from most of the Papal States (Hebraeorum gens, 1569); the war against the Turk was paid for in part by pressure on others."),
 ("war", "Publication",
  "§ 4. Mandantes quibuscumque locorum ordinariis, in virtute sanctae obedientiae, ut statim praesentes litteras vel earum transumpta per suas quisque dioeceses publicari, et etiam per praedicatores ad populi notitiam absque ullo quaestu devenire quamprimum curent et faciant.\n§ 5. Non obstantibus praemissis ac constitutionibus et ordinationibus apostolicis, ceterisque contrariis quibuscumque.\n§ 6. Volumus autem quod praesentium transumptis etc.\nDatum Romae apud S. Petrum, sub annulo Piscatoris, die XII martii MDLXXII, pontificatus nostri anno VII.",
  "§ 4. Commanding all ordinaries of places, in virtue of holy obedience, to see to it at once that these letters or copies of them be published throughout their dioceses, and made known to the people by preachers as soon as possible, without any collection of money.\n§ 5. Notwithstanding the foregoing and apostolic constitutions and ordinances, and all other things to the contrary.\n§ 6. And we will that copies of these presents, etc.\nGiven at Rome at Saint Peter's, under the Fisherman's ring, 12 March 1572, in the seventh year of our pontificate.",
  "'Without any collection of money': the preachers were not to sell the indulgence, a concession to the criticism of the Reformation."),
 # ------------------------------------------------------------ CCXX
 ("captives", "Christians found as slaves among the Turks to be set free",
  "Quod christiani apud Turcas sclavi reperti in bello contra eos parato, liberi cum suis bonis dimittantur ab officialibus classis christianae.\nPius Papa V, ad perpetuam rei memoriam.",
  "That Christians found as slaves among the Turks in the war prepared against them be released free with their goods by the officers of the Christian fleet.\nPius V, Pope, for the perpetual record of the matter.",
  "Undated in the Bullarium, where it stands among Pius V's last constitutions of 1572. The title says 'slaves among the Turks'; the text itself speaks of Christians living in Turkish places."),
 ("captives", "The war's second purpose, and how the victors behave",
  "Licet omnibus notissimum sit bellum hoc, quod cum impio Turcarum tyranno geritur, non ea tantum de causa geri ut imminens ab illius viribus nobis periculum dimoveamus, sed ut etiam plurima christianorum millia, quae sub dira illius tyrannide servilem ac miserabilem vitam ducunt, in libertatem ac ad Christi nomen libere confitendum ac excolendum vindicemus; non defuerunt tamen qui, christianae fraternitatis obliti, loca Turcarum hostium nostrorum invadentes, christianos ibidem repertos in servitutem redegerunt, bonis ac fortunis spoliarunt, triremibus alligarunt, ac talleam imposuerunt, quo fit ut Christi sanguine redempti, qui cumulatis votis christianorum adventum et victoriam exoptaverunt, ea a victoribus fratribus suis patiantur, quibus paulo peiora a Turcis expectare potuissent.",
  "Although it is well known to all that this war, which is waged against the impious tyrant of the Turks, is waged not only to avert the danger that threatens us from his forces, but also to restore to liberty, and to the free confession and worship of the name of Christ, the many thousands of Christians who lead a servile and miserable life under his cruel tyranny: there have nevertheless been those who, forgetful of Christian brotherhood, invading the places of the Turks our enemies, have reduced the Christians found there to servitude, stripped them of their goods and fortunes, chained them to the galleys and imposed ransoms on them; so that those redeemed by the blood of Christ, who with heaped-up prayers longed for the coming and the victory of the Christians, suffer from their victorious brothers things hardly worse than they could have expected from the Turks.",
  "The Christians 'found in the places of the Turks' are above all the Orthodox Greeks of the islands and coasts that the League's galleys raided. Herrera's song reproaches the Greeks for serving the Turk (Herrera Canción [17]); here the Pope reproaches the League's soldiers for enslaving them. The game counts the Christian galley slaves freed at Lepanto; this document shows the other traffic."),
 ("captives", "The decree",
  "§ 1. Nos igitur Eius locum, licet immeriti, tenentes in terris, qui de coelo ad liberandum nos venit, ut, de manu inimicorum nostrorum liberati, deinceps sine timore serviamus Illi, verentes ne, si iniunctae nobis ab eo erga filios nostros caritatis et dilectionis immemores simus, omnipotentis Dei contra nos classemque nostram iram provocemus, malis huiusmodi obviare cupientes, tenore praesentium, decernimus et mandamus ut nullus deinceps sive sacri foederis miles sive alius christianos capiat, aut praeter eorum voluntatem, etiam data mercede, remigare cogat, talleam imponat, aut eius bona diripiat, quinimmo fraterne et amicabiliter, ut christianam pietatem decet, tractet, ac libere cum liberis suis, coniugibus et bonis abire permittat.",
  "§ 1. We therefore, holding on earth, though unworthy, the place of Him who came from heaven to free us, so that, delivered from the hand of our enemies, we might serve Him henceforth without fear; fearing that, if we were unmindful of the charity and love he has enjoined on us toward our sons, we might provoke the wrath of almighty God against us and our fleet; and wishing to meet such evils: by the tenor of these presents we decree and command that henceforth no one, whether a soldier of the holy League or anyone else, shall seize Christians, or force them to row against their will, even for pay, or impose a ransom on them, or plunder their goods; but that he treat them in a brotherly and friendly way, as befits Christian piety, and let them go free with their children, their wives and their goods.",
  "'Force them to row … even for pay': the League's galleys were short of rowers, and pressing men into the oars was the quickest remedy."),
 ("captives", "Excommunication",
  "§ 2. Illos autem omnes et singulos, qui huic constitutioni contraire praesumpserint, declaramus ipso facto in poenam excommunicationis latae sententiae incidisse, a qua non possint, nisi a nobis et successoribus nostris, praeterquam in mortis articulo, absolvi; et ulterius volumus eos a superioribus suis, ad quos spectabit, severe et graviter, iuxta contraventionis qualitatem, puniri.",
  "§ 2. And all and each who presume to act against this constitution we declare to have incurred by that very fact the penalty of excommunication latae sententiae, from which they cannot be absolved except by us and our successors, save at the point of death; and we will further that they be punished severely and gravely by their superiors, whom it concerns, according to the nature of the offence.",
  None),
 ("captives", "To be proclaimed in the fleet, in the people's own language",
  "§ 3. Mandantes omnibus et singulis, tam ipsius classis quam locorum ipsorum superioribus, quibus spectat et in futurum spectabit, ut pro quanto student divinam gratiam nostramque benevolentiam promereri, hoc nostrum, immo vero potius dominicum praeceptum et mandatum, in locis suae iurisdictionis sive iis ad quae christianorum principum foederatorum praefectos, tam generales quam particulares, appellere contigerit, ea lingua cuius eius loci habitatores intelligentes fuerint, et in ipsa etiam classe, publice edi, affigi, et sub poenis sibi bene visis faciant ab omnibus inviolabiliter observari, ut a Deo Opt. Max. praemia aeterna et a nobis de re diligenter gesta laudem reportare mereantur.\n§ 4. Volumus autem ut praesentis nostri motus proprii sola signatura sufficiat et ubique fidem faciat, in iudicio et extra, quacumque regula seu constitutione apostolica contraria non obstante.\n§ 5. Quodque illius exempla, etiam impressa, edantur, eaque notarii publici manu et cuiuscumque curiae ecclesiasticae aut praelati sigillo obsignata, eamdem prorsus fidem ubique faciant, quam ipse praesens motus proprius faceret, si esset exhibitus vel ostensus; contrariis non obstantibus quibuscumque.\nFiat. Motu proprio, M.",
  "§ 3. Commanding all and each of the superiors, both of the fleet itself and of the places themselves, whom it concerns and shall concern in future, as they seek to deserve divine grace and our goodwill, to have this our command, or rather the Lord's precept and mandate, published and posted in the places of their jurisdiction, or in those at which the commanders of the confederate Christian princes, general or particular, happen to put in, in the language that the inhabitants of that place understand, and in the fleet itself, and to have it observed inviolably by all under penalties at their discretion; so that they may deserve eternal rewards from God, Best and Greatest, and praise from us for a matter diligently done.\n§ 4. And we will that the signature alone of this our motu proprio suffice and be believed everywhere, in court and out of it, notwithstanding any rule or apostolic constitution to the contrary.\n§ 5. And that copies of it, printed ones too, be issued, and that those signed by the hand of a public notary and sealed with the seal of any ecclesiastical court or prelate have everywhere exactly the same credit as this motu proprio would have if it were produced or shown; all things to the contrary notwithstanding.\nLet it be done. Motu proprio, M.",
  "'In the language the inhabitants understand': Greek, on the islands and coasts where the League's galleys put in."),
 # ------------------------------------------------------------ Monet Apostolus
 ("feast", "The feast of the Rosary, for the victory of 7 October",
  "Institutio festivitatis sub invocatione Rosarii B. Mariae Virginis, prima dominica die mensis octobris, in ecclesiis vel cappellis Rosarii duplici maiori officio celebrandae, pro gratiarum actione de victoria die VII dicti mensis octobris parta contra Turcas.\nGregorius episcopus servus servorum Dei, ad perpetuam rei memoriam.",
  "Institution of a feast under the title of the Rosary of the Blessed Virgin Mary, to be celebrated on the first Sunday of the month of October, in churches or chapels of the Rosary, with a double major office, in thanksgiving for the victory won against the Turks on 7 October of that month.\nGregory, bishop, servant of the servants of God, for the perpetual record of the matter.",
  "Gregory XIII succeeded Pius V in May 1572. His bull is dated 1 April 1573, three and a half weeks after Venice had made its separate peace with the Sultan in Istanbul on 7 March 1573 (Tuhfe 1572–73 [2]). The League was ending; the feast remained. The Bullarium notes: 'this feast is commonly called Saint Mary of Victory'."),
 ("feast", "Why feasts are kept",
  "Monet Apostolus in omnibus gratias agere; monent quoque sacrarum litterarum historiae insignia Dei beneficia, tum ut ei, a quo accepta sunt, meritae referantur gratiae, tum ut fideles, quibus collata sunt, illorum memores, ad divinum cultum magis in dies excitentur, solemnibus annuis festivitatibus celebranda esse. Quod cum multoties institutum fuerit, tum vero maxime cum Deus patrum nostrorum populum suum a servitute Aegyptiaca per manum fortem liberavit.",
  "The Apostle bids us give thanks in all things; and the histories of Holy Scripture also bid us celebrate God's signal benefits with solemn yearly feasts, both so that due thanks may be rendered to him from whom they were received, and so that the faithful on whom they were conferred, remembering them, may be roused more every day to divine worship. This was done many times, but above all when the God of our fathers freed his people from the servitude of Egypt with a mighty hand.",
  "The Exodus again, as in Herrera's song (Herrera Canción [1]): Lepanto is read as a deliverance from Egypt. 'The Apostle': 1 Thessalonians 5:18."),
 ("feast", "The victory",
  "§ 1. Nos itaque, qui non minora beneficia quotidie a Deo optimo maximo accipimus, inter quae illud singularissimum superiore anno ab ineffabili ipsius clementia nobis concessum fuit, ut Turcarum classis, et numero longe superior et praeteritis elata victoriis, a christianorum classe in virtute Domini Dei Sabaoth decertante, die VII octobris, non longe a Corinthiaco sinu penitus devicta et quassata fuerit; qua nempe victoria universum populum christianum ab impiissimi tyranni faucibus divino munere ereptum fuisse inficiari nemo potest; Apostoli praecepto parere, et sanctorum Patrum exempla sequi volentes, ut huius ingentissimi beneficii anniversaria habeatur memoria instituere omnino decrevimus.",
  "§ 1. We therefore, who daily receive no lesser benefits from God, best and greatest, among which that most singular one was granted us in a former year by his ineffable mercy, that the fleet of the Turks, far superior in number and elated by past victories, was utterly defeated and shattered on 7 October, not far from the Gulf of Corinth, by the fleet of the Christians fighting in the strength of the Lord God of Hosts; by which victory no one can deny that the whole Christian people was snatched by divine gift from the jaws of a most impious tyrant; wishing to obey the Apostle's precept and follow the example of the holy Fathers, have wholly resolved to institute a yearly memorial of this most immense benefit.",
  "'Superiore anno' usually means 'last year'; written in April 1573, of October 1571, it is taken here loosely. 'Far superior in number': the same claim as Herrera and Contarini; the numbers were in fact close."),
 ("feast", "Saint Dominic and the Rosary",
  "§ 2. Quia vero preces ad Deum oblatae eo gratiores ad illius conspectum ascendunt, quo dignioribus intercessoribus et pio aliquo orandi modo offeruntur, memores beatum Dominicum Ordinis Praedicatorum institutorem, cum et Gallia et Italia a perniciosis premeretur haeresibus, ad iram Dei placandam et Beatissimae Virginis intercessionem implorandam, piissimum illum orandi modum instituisse, quod Rosarium seu Psalterium Beatissimae Virginis Mariae nuncupatur.",
  "§ 2. And since prayers offered to God rise the more pleasingly before him the worthier the intercessors and the more pious the manner of praying with which they are offered; remembering that blessed Dominic, founder of the Order of Preachers, when both France and Italy were oppressed by pernicious heresies, instituted, to appease the wrath of God and implore the intercession of the most blessed Virgin, that most pious manner of praying which is called the Rosary or Psalter of the most blessed Virgin Mary;",
  "Pius V was a Dominican. The attribution of the Rosary to Saint Dominic is the tradition of the order, which Pius V had confirmed in 1569."),
 ("feast", "The processions of 7 October",
  "§ 3. Animadvertentes quoque eadem die septima, quae tunc fuit dies dominica prima dicti mensis octobris, fraternitates omnes sub dicti Rosarii nuncupatione militantes per universum orbem, iuxta earum laudabilia instituta et consuetudines, processionaliter incedentes, pias ad Deum preces effudisse, quas per intercessionem Beatissimae Virginis ad dictam victoriam consequendam multum profuisse pie credendum est; operae pretium nos facturos esse existimavimus, si ad tantae victoriae coelitus proculdubio concessae memoriam conservandam, et ad gratias Deo et Beatissimae Virgini agendas, festum solemne sub nuncupatione Rosarii, prima dominica mensis octobris singulis annis celebrandum, institueremus.",
  "§ 3. Noting also that on that same seventh day, which was then the first Sunday of the said month of October, all the confraternities serving under the title of the said Rosary throughout the world, walking in procession according to their praiseworthy statutes and customs, poured out pious prayers to God, which it is piously to be believed helped much, through the intercession of the most blessed Virgin, to win the said victory: we thought it worthwhile, to preserve the memory of so great a victory, beyond doubt granted from heaven, and to give thanks to God and the most blessed Virgin, to institute a solemn feast under the title of the Rosary, to be celebrated every year on the first Sunday of October.",
  "7 October 1571 was the first Sunday of October, the day of the Rosary confraternities' processions; Herrera gives the day as the feast of Saint Mark, pope (Herrera Meeting [1]). The memory of the battle was attached to a prayer said on the same day far away."),
 ("feast", "The decree",
  "§ 4. Quocirca motu proprio et de apostolicae potestatis plenitudine, ad laudem Dei et Domini nostri Iesu Christi, eiusque gloriosae Virginis Matris, tenore praesentium, decernimus ut de cetero, perpetuis futuris temporibus, qualibet prima die dominica mensis octobris, per universi orbis partes, in iis videlicet ecclesiis, in quibus altare vel cappella Rosarii fuerit, ab omnibus et singulis utriusque sexus christifidelibus, festum solemne, sub nuncupatione Rosarii praedicti, sub duplici maiori officio, ad instar aliarum solemnium festivitatum, celebretur et sanctificetur; eademque die Officium de Beatissima Virgine novem lectionum more ecclesiastico persolvatur et recitetur.",
  "§ 4. Wherefore, of our own motion and from the fullness of apostolic power, to the praise of God and of our Lord Jesus Christ and of his glorious Virgin Mother, by the tenor of these presents we decree that henceforth, for all time to come, on every first Sunday of the month of October, throughout all parts of the world, namely in those churches in which there is an altar or chapel of the Rosary, a solemn feast under the title of the said Rosary be celebrated and kept holy by all and each of the faithful of either sex, with a double major office, like the other solemn feasts; and that on that day the Office of the most blessed Virgin of nine lessons be said and recited in the manner of the Church.",
  "At first the feast was kept only where there was a Rosary altar. It was extended to Spain in 1671, to the whole Church in 1716 after another victory over the Ottomans, at Petrovaradin, and moved to 7 October in 1913, where it remains as Our Lady of the Rosary."),
 ("feast", "Clauses and date",
  "§ 5. Decernentes praesentes, quas perpetuo valere volumus, nullo umquam tempore de subreptionis vel obreptionis aut nullitatis seu alio vitio, vel intentionis nostrae aut alio defectu notari, argui vel impugnari posse, sed plenarios effectus sortiri debere. […]\n§ 7. Contrariis quibuscumque non obstantibus.\n§ 8. Volumus autem quod praesentium transumptis etc.\nDatum Romae apud Sanctum Petrum, sub annulo Piscatoris, die I aprilis MDLXXIII, pontificatus nostri anno I.",
  "§ 5. Decreeing that these presents, which we will to be valid for ever, can never at any time be marked, challenged or impugned for surreption or obreption, nullity or any other defect, or for any defect of our intention, but must have their full effect. […]\n§ 7. All things to the contrary notwithstanding.\n§ 8. And we will that copies of these presents, etc.\nGiven at Rome at Saint Peter's, under the Fisherman's ring, 1 April 1573, in the first year of our pontificate.",
  "The standard clause § 6 on judges is left out […]. The perpetual feast was founded in the same weeks in which the perpetual League of the capitulations (Liga Forces [1]) came to its end."),
]

SECTIONS = [
  ("prisoners", "Pius V (21 December 1571): keep the Turkish prisoners", "Pius Prisoners",
   "Ten weeks after the battle the Pope learns that the victors are keeping, selling and ransoming their Ottoman prisoners. He forbids any release while the war lasts, because the prisoners are seamen the enemy badly needs, and orders a register sent to Rome."),
  ("war", "Pius V, Cum nos (12 March 1572): pay for the war", "Pius War",
   "Five months after the battle, the Pope as a confederate prince calls on all the faithful to continue the war in person or with their money, and grants them the crusade indulgence, suspension of lawsuits and release from usury, enforced against the Jews."),
  ("captives", "Pius V (1572): do not enslave the Christians you find", "Pius Captives",
   "The war was fought to free the Christians under the Sultan; but the League's soldiers, raiding Ottoman places, have enslaved the Christians they found there, chained them to the oars and ransomed them. The Pope forbids it on pain of excommunication, to be proclaimed in the fleet and in the people's own language."),
  ("feast", "Gregory XIII, Monet Apostolus (1 April 1573): the feast", "Gregory Feast",
   "Three and a half weeks after Venice's separate peace, the new Pope institutes a yearly feast of the Rosary on the first Sunday of October, because the Rosary confraternities had walked in procession on the day of the battle. The League ended; the feast is still kept."),
]


def main():
    sections = []
    for sid, titel, zk, blurb in SECTIONS:
        units = []
        for s, label, la, en, note in PRISONERS + UNITS:
            if s != sid:
                continue
            u = {"n": len(units) + 1, "orig": la, "en": en}
            if label:
                u["titel"] = label
            if note:
                u["note"] = note
            units.append(u)
        units[0]["label"] = True
        sections.append({"id": sid, "titel": titel, "zk": zk, "blurb": blurb, "units": units})
    doc = {
        "id": "pius",
        "titel": "The Popes after the Victory: Prisoners, War, Captives and the Feast",
        "autor": "Pius V (pope 1566–1572) and Gregory XIII (pope 1572–1585)",
        "jahr": "1571–1573",
        "sprache": "en",
        "orig_sprache": "la",
        "zk": "Pius",
        "quelle": "Bullarum diplomatum et privilegiorum sanctorum Romanorum pontificum Taurinensis editio, vol. VII (Turin, 1862), pp. 957–958 (Pius V, const. CCXIII), 967–969 (Pius V, const. CCXVII, Cum nos) and 972–973 (Pius V, const. CCXX); vol. VIII (Turin, 1863), pp. 44–46 (Gregory XIII, const. XVII, Monet Apostolus); Internet Archive 04672031.7.emory.edu and 04672031.8.emory.edu (Emory University, Pitts Theology Library).",
        "hinweis": "The voice of the player's office. In the game you are the Papacy holding the League together; here the Popes speak in their own documents after the victory: Pius V forbidding the release of the Ottoman prisoners, who were seamen the enemy needed, Pius V raising money and men to continue the war, Pius V forbidding the League's soldiers to enslave the Christians they found in Ottoman lands, and Gregory XIII founding the feast by which the day was remembered. Pius V's own first commemoration, a feast of Our Lady of Victory, is not in the Bullarium and is not carried. The Latin is that of the nineteenth-century Turin edition, corrected against the page images; its marginal summaries are left out. One clause of Cum nos, against the Jews, is carried as printed and explained in the note. The English is this site's working translation (CC0).",
        "sections": sections,
    }
    OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"pius.json: {sum(len(s['units']) for s in sections)} units")


if __name__ == "__main__":
    main()
