"""Pius V, constitution CCXIII (21 December 1571), Bullarium Taurinense vol. VII,
pp. 957–958 (scan n967–n968): Turkish prisoners not to be released or sold while
the war lasts. Imported by build-pius.py; same conventions."""

PRISONERS = [
 ("prisoners", "Turks taken in the war not to be released or sold while it lasts",
  "Turcae, qui in bello contra eos peracto captivi sunt effecti, durante bello non dimittantur neque distrahantur.\nPius Papa V, motu proprio, etc.",
  "That the Turks who were taken prisoner in the war fought against them be neither released nor sold while the war lasts.\nPius V, Pope, of his own motion, etc.",
  "Dated 21 December 1571, ten weeks after the battle."),
 ("prisoners", "The victory, and what the victors did with their prisoners",
  "Postquam nuper inter nos et Sedem Apostolicam ac carissimum in Christo filium nostrum Philippum Hispaniarum regem catholicum, necnon dilectum filium nobilem virum Aloysium Mocenicum Venetorum ducem et eius reipublicae dominium, inito foedere, et classe communibus viribus comparata, dilecto filio nobili viro Ioanni ab Austria, eius generali praefecto et ductori, commissum fuit praelium omni posteritati commemorandum, initio illud quidem, quatenus poteramus nobis ab humanis viribus polliceri, periculosissimum, ipso autem exitu felicissimum, hostibus in maximam partem caesis, fugatis, reliquis captivis factis (causam nimirum suam Domino Deo nostro iuvante, proque suo Israele pugnante), perlatum fuit ad nos plerosque christianorum, partim captivos illos sibi ipsis retinuisse, partim vendidisse, alios donasse, nonnullos etiam, pacta pecunia, in spem redemptionis adduxisse.\n§ 1. Quod sane graviter, ut debuimus, accepimus, ab ipsa enim superiorum temporum experientia edocti sumus, quanto semper haec cum christianorum damno facta fuerint; plerosque enim ipsorum captivorum esse navigandi peritissimos, ad classem adornandam, instruendam, ducendam, propter multam maris tempestatum orarumque peritiam, atque ad bellandum utilissimos, et si umquam alias, certe hoc tempore, ceteris suis similibus caesis, esse hostibus pernecessarios, ex quorum missione, ut magna decessio, cum etiam ab omni ratione et iure belli alienissimum sit ut, ipso bello durante, mittantur illi, qui possunt aliquando ipsis mittentibus bellum instaurare et contra eos venire.",
  "After a league had lately been made between us and the Apostolic See and our most dear son in Christ Philip, Catholic King of the Spains, and our beloved son the noble Alvise Mocenigo, Doge of the Venetians, and the lordship of his republic, and a fleet assembled with common forces, a battle to be remembered by all posterity was fought under our beloved son the noble John of Austria, its general commander and leader: at the outset most dangerous, as far as we could promise ourselves from human strength, but in its outcome most happy, the enemy being for the most part killed or put to flight and the rest taken prisoner (the Lord our God helping his own cause and fighting for his Israel). It has been reported to us that many Christians have in part kept those prisoners for themselves, in part sold them, given others away, and even led some, for an agreed sum of money, to hope for ransom.\n§ 1. This we have taken gravely, as we ought; for we have been taught by the experience of former times how much harm this has always done to the Christians. Many of these prisoners are most skilled in navigation, most useful for fitting out, equipping and leading a fleet, through their great knowledge of the sea's storms and coasts, and for fighting; and now, if ever, with the others like them killed, they are most necessary to the enemy. Their release would be a great loss [to us], since it is utterly contrary to all reason and to the law of war that, while the war itself lasts, men should be sent back who may one day renew the war against those who sent them, and come against them.",
  "Contarini's division of the spoils counts the prisoners as 'slaves' shared among the three partners (Contarini Reckoning [5]). The Pope's reason is the one that decided the war: seamen, not hulls, were the Ottomans' shortage, and the winter of 1571–72 rebuilt the hulls (Peç. Fleet [3]; Tuhfe Fleet [3]). The sentence 'ex quorum missione, ut magna decessio' is incomplete as printed."),
 ("prisoners", "Keep them, and report them to Rome",
  "§ 2. Quod quidem malum, tametsi dilectum filium nobilem virum Ioannem ab Austria, pro eius singulari prudentia, praevidisse eique providisse non dubitamus; tamen, ut ad eius cautionem apostolicae etiam auctoritatis robur accedat, praecipimus et mandamus omnibus et singulis, quocumque sint gradu, conditione, statu, nomine, honore, apud quos captivi aliqui ex classe Turcarum, vel nunc sunt, vel in posterum erunt, sive ipsi eos receperint, sive ab aliis emptione, donatione, permutatione vel alia quacumque ratione acceperint, ne illos, hoc foedere et bello durante, quocumque nomine, ratione, colore, mittere, alienare, liberare, fugere atque abire permittere audeant, sed eos debeant omni cura et diligentia custodire; et eorum numerum, nomina, patriam, parentes, aetatem, dignitatem, sive conditionem et alias, si quae extant, magis certae et particulares demonstrationes nobis aut nostris nunciis, si ibi praesentes fuerint, si vero absentes, ipsarum civitatum et locorum, in quibus dictos captivos habentes reperiuntur, rectoribus, gubernatoribus, iudicibus, locatenentibus aut alio nomine nuncupatis, in ipsa vero classe existentes, nostris aut nostrorum foederatorum ductoribus, praefectis, iudicibus, quam primum a publicatione praesentium indicare. Illi autem, quibus captivi praedicti fuerint indicati, debeant similiter eorum numerum et ceteras omnes circumstantias supradictas, prout eas acceperint, nobis quanto citius significare.",
  "§ 2. And although we do not doubt that our beloved son the noble John of Austria, in his singular prudence, has foreseen this evil and provided against it, nevertheless, so that the strength of apostolic authority may be added to his precaution, we order and command all and each, of whatever rank, condition, state, name or honour, with whom any prisoners from the Turkish fleet now are or shall be hereafter, whether they took them themselves or received them from others by purchase, gift, exchange or in any other way, that while this league and war last they do not dare, under any name, reason or pretext, to send them away, alienate them, free them or let them escape and go, but keep them with all care and diligence; and that, as soon as these presents are published, they report their number, names, country, parents, age, rank or condition, and any other more certain and particular marks there may be, to us or to our nuncios, if they are present there; if absent, to the rectors, governors, judges, lieutenants, or whatever they are called, of the cities and places where those who hold the prisoners are found; and those in the fleet itself, to the commanders, officers and judges of ourselves or of our confederates. And those to whom the prisoners have been reported must likewise inform us as quickly as possible of their number and all the other particulars above, as they have received them.",
  "A register of the prisoners, to be sent to the Pope: the Papacy as the League's accountant. Ali Pasha's sons were among the prisoners of rank (Herrera Battle [9])."),
 ("prisoners", "Penalties",
  "§ 3. Si qui vero ex praedictis contravenerint, eos excommunicationis maioris latae sententiae, a qua nisi a nobis ac successoribus nostris canonice intrantibus absolvi nequeant, necnon amissionis omnium et singulorum feudorum, dominiorum et aliorum quorumcumque bonorum, tam mobilium quam immobilium, quoad eos, qui ecclesiasticae iurisdictionis fuerint, nobis et fisco nostro; qui vero aliarum ditionum, suae cuiusque ditionis fisco applicandorum, et laesae etiam maiestatis criminis poena eo ipso incurrisse declaramus; sperantes etiam quod dicti nostri foederati huiusmodi nostrum praeceptum in suis quisque locis inviolabiliter observari curabunt. […]\nFiat. Motu proprio, M.\nDatum Romae apud S. Petrum, duodecimo kalendas ianuarii, anno VI.",
  "§ 3. And if any of the aforesaid act against this, we declare that they have by that very fact incurred the penalty of the greater excommunication latae sententiae, from which they cannot be absolved except by us and our successors canonically entering office; the loss of each and all of their fiefs, lordships and any other goods, movable and immovable, to go, for those under ecclesiastical jurisdiction, to us and our treasury, for those of other dominions, to the treasury of each one's dominion; and the penalty of the crime of lèse-majesté as well; hoping also that our said confederates will see to it that this our command is inviolably observed each in his own lands. […]\nLet it be done. Motu proprio, M.\nGiven at Rome at Saint Peter's, on the twelfth day before the Kalends of January, in the sixth year [21 December 1571].",
  "The clauses of execution and derogation (§§ 4–7) are left out […]. The Pope could command in his own lands; for the rest he could only hope that the confederates would enforce it."),
]
